### PR TITLE
Decompose forward function into initialize, predict, update

### PR DESCRIPTION
**Pull request by THargreaves**
As discussed in #104, this PR takes the existing forward filtering code and decomposes it into separate functions for initialising the filter, predicting the next state and updating the filtered state.

There are a few mildly ugly corners:
- `logL` is passed into `_update!` and returns. This is because the `logL` in storage is not updated until the full forward filtering is completed. This could be resolved by passing a `k` argument into `forward!` and updating `logL[k]` in-place but changing this signature had knock on effects on other algorithms (e.g. Baum-Welch) so I've left for now
- The prediction step is skipped for `t=1` since we just use the initialisation value. 

On the bright side, this decomposition has made the indexing a bit easier to understand. The loop is now `t1:t2` and the main index used is `t` rather than `t+1` before.

All correctness tests pass but there are few test cases in the AD/temporal examples that are failing. Happy to look into these but @gdalle might be able to instantly spot what's wrong.

### CODE REVIEW

**Comment by gdalle** [comment]
@THargreaves what do you think? Are these the functions you would need to be part of the public API?

**Comment by THargreaves** [comment]
Yes, those are perfect. Thank you for making the changes!

I'm not sure if they necessarily need to be part of the public API as we'll be wrapping them to match our slightly different type signature. If that's the easiest way to make sure these methods don't change though that might be best.

**Comment by gdalle** [comment]
Indeed if it's not part of the public API then it is vulnerable to change at any second. My suggestion is that I'll first release a new version of HMMs including them as private API, that way you can experiment and see what's missing. Once your code stabilizes, we'll figure out the best way to make its ingredients public API in HMMs.

**Comment by THargreaves** [comment]
Sounds like a plan 👍

**Pull request merged**
